apiVersion: batch/v1
kind: Job
metadata:
  name: v1dd-transfer

spec:
  parallelism: 135
  backoffLimit: 4

  template:
    metadata:
      labels:
        app: v1dd-transfer
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: v1dd-transfer-workers

      restartPolicy: Never

      containers:
      - name: v1dd-transfer
        image: us-west1-docker.pkg.dev/gcp-redd-bossdb/v1dd-transfer/v1dd-transfer:latest
        env:
        - name: QUEUE
          value: "https://sqs.us-east-1.amazonaws.com/407510763690/s3-transfer-downsample"

      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app: v1dd-transfer
